config:
  - ["C",32, 3, 1]
  - ["C",64, 3, 2]
  - ["B", 1]

  - ["C",128, 3, 2]
  - ["B", 2]

  - ["C",256, 3, 2]
  - ["B", 8]
  - [A,1]
  - ["C",512, 3, 2]
  - ["B", 8]


  - ["C",1024, 3, 2]
  - ["B", 4]


  # YOLO-53 biter
  - ["C",512, 1, 1]
  - ["C",1024, 3, 1]
  - "S"

  - ["C",256, 1, 1]
  - "U"
  - ["C",256, 1, 1]
  - ["C",512, 3, 1]
  - "S"

  - ["C",128, 1, 1]
  - "U"
  - ["C",128, 1, 1]
  - ["C",256, 3, 1]
  - "S"
